### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by codefromthecrypt** [F21/javy-wazero#2]
I think it would be great to show why this is important with benchmarks. You could just host the code for them or put results in the README. I don't think it is easy for people to understand how important this change is without seeing it.

You can look in wazero's [internal/integration_test/vs](https://github.com/tetratelabs/wazero/blob/main/internal/integration_test/vs/bench.go) directory as we had broken things down in a few ways which are likely important to you here also. Ex compile vs instantiate vs call

Personally, I would like to see these so I can help with any wazero-optimizations and know the context of the change, ex does it matter.

**Comment by codefromthecrypt** [comment]
sorry by "this change" I meant Shopify vs suborbital

**Comment by F21** [comment]
Good idea! Benchmarks committed in ee591c0a3f20ea35c40e362041989f292cf6e7ea.

It shows a massive difference between how cheap `Call()` is vs `InstantiateModule()`

**Comment by codefromthecrypt** [comment]
I think you might have a bug in Call as it seems too fast. I'd love to take credit for it, but heh

**Comment by F21** [comment]
Hmm. Can you check the `*_test.go` files to see if the tests are indeed buggy? If I run `example.go` and print out the time taken for each version of Javy, `Call()` is way faster than `InstantiateModule()`:
```
$ cd shopify-javy
$ go run example.go
{"greeting":"Hello Person 0!"} Time taken: 2.8012ms
{"greeting":"Hello Person 1!"} Time taken: 2.8623ms
{"greeting":"Hello Person 2!"} Time taken: 1.9897ms
{"greeting":"Hello Person 3!"} Time taken: 2.7312ms
{"greeting":"Hello Person 4!"} Time taken: 4.3611ms
{"greeting":"Hello Person 5!"} Time taken: 2.9188ms
{"greeting":"Hello Person 6!"} Time taken: 2.8985ms
{"greeting":"Hello Person 7!"} Time taken: 3.3523ms
{"greeting":"Hello Person 8!"} Time taken: 1.8676ms
{"greeting":"Hello Person 9!"} Time taken: 3.3348ms
$ cd ../suborbital-javy
$ go run example.go
{"greeting":"Hello Person 0!"} Time taken: 342.6µs
{"greeting":"Hello Person 1!"} Time taken: 224.9µs
{"greeting":"Hello Person 2!"} Time taken: 236.1µs
{"greeting":"Hello Person 3!"} Time taken: 278.2µs
{"greeting":"Hello Person 4!"} Time taken: 220.4µs
{"greeting":"Hello Person 5!"} Time taken: 345.8µs
{"greeting":"Hello Person 6!"} Time taken: 180.1µs
{"greeting":"Hello Person 7!"} Time taken: 283.9µs
{"greeting":"Hello Person 8!"} Time taken: 360µs
{"greeting":"Hello Person 9!"} Time taken: 197.1µs
```

**Comment by codefromthecrypt** [comment]
made a note in the commit. the README has times <1ns which is why I thought maybe there was a bug
